baseurl = "http://www.meishinmusoryu.com/"
languageCode = "en-us"
title = "Meishin Muso Ryu"
theme = "hugo-strata-theme"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
# Change Hugo publish directory to docs, so website can be deployed to GitHub Pages
publishDir = "docs"
relativeURLs = "true"

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Meishin Muso Ryu"
	description = "Official website of Meishin Muso Ryu (明神無想流), an Iaido style passed down from Shinkage Ryu (神影流)"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = ["css/custom.css"]


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.png"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**MEISHIN MUSO RYU**<br> Anytime, Anyplace, Any Situation"
		# The icons will be shown if you enter your username
		twitter = "shudokandojo"
		youtube = "MeishinMusoRyu"
		github = ""
		gitlab = ""
		dribbble = ""
		facebook = "MeishinMusoRyu"
		googleplus = ""
		flickr = ""
		linkedin = ""

		copyright = [
			"&copy; Meishin Ryu Sogo Budo Renmei",
			"Website made by: [Gary Pang](//codewritingcow.com)"
		]
	
	[params.rss]
		# RSS icon will be shown in sidebar if set to false
		hide = true

	[params.about]
		hide  = false
		title = "Meishin Muso Ryu"
		content = "<p>Meishin Muso Ryu (明神無想流) is an Iaido style passed down from Shinkage Ryu (神影流). Our head is <a href='/instructors/'>Matsushita Shuji Sensei.</a></p><p>We teach Iaido and Kendo classes. Our dojo is in the Poconos region of Pennsylvania. We invite you to train with us.</p>"


	[params.portfolio]
		hide  = false
		title = "Photos"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Iaido Demonstration in Japan"
			description = "Matsushita Sensei demonstrates Iaido"

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Meishin Muso Ryu Seminar 2014"
			description = "Group picture from our first seminar"

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Philadelphia Cherry Blossom Festival 2014"
			description = "Tom Hill performs Iaido"

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Philadelphia Cherry Blossom Festival 2015"
			description = "Three-Person Iaido demonstration"

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Scene from *Budo*"
			description = "Matsushita Sensei performs *chiburi*"

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Scene from *Budo*"
			description = "Matsushita Sensei (right) and Fukaya Sensei spar"

	[params.recentposts]
		hide  = true
		title = "Recent blog posts"
	
	[params.schedule]
		hide = false
		title = "Class Schedule"
		content = "<h3>Iaido (Japanese Swordsmanship)</h3><p>Mondays: 6&ndash;7 p.m. Sundays: 7&ndash;8:30 a.m.</p><h3>Kendo (Japanese Fencing)</h3><p>Mondays: 7&ndash;8 p.m. Wednesdays: 8&ndash;9 p.m. Fridays: 8&ndash;9:30 p.m. Sundays: 8:30&ndash;10 a.m.</p><p>To join a class, please call Tom Hill <a href=\"tel:+1-570-350-8072\">(570) 350-8072</a> or Katsunori Matsushita <a href=\"tel:+1-570-269-0050\">(570) 269-0050</a></p>"

	[params.directions]
		hide = false
		title = "Directions"
		content = "<p>Our dojo is at the rear of 831-D Ann St., Stroudsburg, PA. Off-street parking is available. Look for a sign that says \"Ensley's Martial Arts.\"</p><p>We are located near Interstate 80, exit 307. We are an hour away from Wilkes-Barre and Scranton; and 1 hour 30 minutes from New York City.</p>"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "Do you have questions about Iaido or Kendo? Please submit your questions with the form below. We will respond as soon as possible."

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = "40.982062,-75.197148"
		address = [
			"831-D Ann St.",
			"Stroudsburg, PA 18360",
			"United States"
		]
		phone = "+1-570-350-8072"
		phonename = "Tom Hill"
		phone2 = "+1-570-269-0050"
		phonename2 = "Katsunori Matsushita"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "codewritingcow@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "Instructors"
	url  = "instructors/"
	weight = 0	

[[menu.main]]
	name = "Members"
	url  = "members/"
	weight = 0		

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 0	

[[menu.main]]
	name = "Videos"
	url  = "videos/"
	weight = 0			